export const SWIMLINE_DATA_LOAD_START ='SWIMLINE_DATA_LOAD_START';
export const SWIMLINE_DATA_LOAD_SUCCESS = 'SWIMLINE_DATA_LOAD_SUCCESS';
export const SWIMLINE_DATA_LOAD_FAIL ='SWIMLINE_DATA_LOAD_FAIL';

export const INFINITE_SWIMLINE_DATA_LOAD_START = "INFINITE_SWIMLINE_DATA_LOAD_START";
export const INFINITE_SWIMLINE_DATA_LOAD_SUCCESS = "INFINITE_SWIMLINE_DATA_LOAD_SUCCESS";
export const INFINITE_SWIMLINE_DATA_LOAD_FAIL = "INFINITE_SWIMLINE_DATA_LOAD_FAIL";

export const INFINITE_SWIMLINE_TILE_DATA_LOAD_START = "INFINITE_SWIMLINE_TILE_DATA_LOAD_START";
export const INFINITE_SWIMLINE_TILE_DATA_LOAD_SUCCESS = "INFINITE_SWIMLINE_TILE_DATA_LOAD_SUCCESS";
export const INFINITE_SWIMLINE_TILE_DATA_LOAD_FAIL = "INFINITE_SWIMLINE_TILE_DATA_LOAD_FAIL";

export const SET_MODAL_IMAGE = 'SET_MODAL_IMAGE';
